# Site settings
title:          MSM-Xtended
description:    "Custom ROM redefined"
baseurl:        ""
url:            "blog.msmxtended.me"

# Google Analytics
google_analytics: UA-151899301-1

# Author
author:
  name:         MSM-Xtended
  url:          https://msmxtended.me
  email:        msmxtended@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile ]

plugins:
  - jekyll-paginate
  - jekyll-remote-theme